// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolERPManagementDALLibrary.Contexts;

#nullable disable

namespace SchoolERPManagementDALLibrary.Migrations
{
    [DbContext(typeof(SchoolERPDbContext))]
    [Migration("20260604113434_AddStaffAttendance")]
    partial class AddStaffAttendance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Academicyear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Enddate")
                        .HasColumnType("date")
                        .HasColumnName("enddate");

                    b.Property<bool?>("Iscurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("iscurrent");

                    b.Property<DateOnly>("Startdate")
                        .HasColumnType("date")
                        .HasColumnName("startdate");

                    b.Property<string>("Yearname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("yearname");

                    b.HasKey("Id")
                        .HasName("academicyears_pkey");

                    b.ToTable("academicyears", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Assetname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("assetname");

                    b.Property<int?>("Assettypeid")
                        .HasColumnType("integer")
                        .HasColumnName("assettypeid");

                    b.Property<int?>("Assignedclassid")
                        .HasColumnType("integer")
                        .HasColumnName("assignedclassid");

                    b.Property<DateOnly?>("Purchasedate")
                        .HasColumnType("date")
                        .HasColumnName("purchasedate");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("Warrantyexpiry")
                        .HasColumnType("date")
                        .HasColumnName("warrantyexpiry");

                    b.HasKey("Id")
                        .HasName("assets_pkey");

                    b.HasIndex("Assettypeid");

                    b.HasIndex("Assignedclassid");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Assetreport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Assetid")
                        .HasColumnType("integer")
                        .HasColumnName("assetid");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Report")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("report");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("assetreports_pkey");

                    b.HasIndex("Assetid");

                    b.ToTable("assetreports", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Assettype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Typename")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("typename");

                    b.HasKey("Id")
                        .HasName("assettypes_pkey");

                    b.HasIndex(new[] { "Typename" }, "assettypes_typename_key")
                        .IsUnique();

                    b.ToTable("assettypes", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("Markedbyteacherid")
                        .HasColumnType("integer")
                        .HasColumnName("markedbyteacherid");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("Studentid")
                        .HasColumnType("integer")
                        .HasColumnName("studentid");

                    b.HasKey("Id")
                        .HasName("attendance_pkey");

                    b.HasIndex("Markedbyteacherid");

                    b.HasIndex(new[] { "Studentid", "Date" }, "attendance_studentid_date_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Studentid", "Date" }, "idx_attendance_student_date");

                    b.ToTable("attendance", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Classname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("classname");

                    b.Property<int?>("Classteacherid")
                        .HasColumnType("integer")
                        .HasColumnName("classteacherid");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("section");

                    b.HasKey("Id")
                        .HasName("classes_pkey");

                    b.HasIndex("Classteacherid");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Academicyearid")
                        .HasColumnType("integer")
                        .HasColumnName("academicyearid");

                    b.Property<string>("Examname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("examname");

                    b.HasKey("Id")
                        .HasName("exams_pkey");

                    b.HasIndex("Academicyearid");

                    b.ToTable("exams", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Examresult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Examid")
                        .HasColumnType("integer")
                        .HasColumnName("examid");

                    b.Property<decimal?>("Marks")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("marks");

                    b.Property<int>("Studentid")
                        .HasColumnType("integer")
                        .HasColumnName("studentid");

                    b.Property<int>("Subjectid")
                        .HasColumnType("integer")
                        .HasColumnName("subjectid");

                    b.Property<string>("Uploadedcorrectedanswersheeturl")
                        .HasColumnType("text")
                        .HasColumnName("uploadedcorrectedanswersheeturl");

                    b.HasKey("Id")
                        .HasName("examresults_pkey");

                    b.HasIndex("Subjectid");

                    b.HasIndex(new[] { "Examid", "Subjectid", "Studentid" }, "examresults_examid_subjectid_studentid_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Studentid" }, "idx_examresults_student");

                    b.ToTable("examresults", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Examschedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Classid")
                        .HasColumnType("integer")
                        .HasColumnName("classid");

                    b.Property<int>("Durationminutes")
                        .HasColumnType("integer")
                        .HasColumnName("durationminutes");

                    b.Property<DateOnly>("Examdate")
                        .HasColumnType("date")
                        .HasColumnName("examdate");

                    b.Property<int>("Examid")
                        .HasColumnType("integer")
                        .HasColumnName("examid");

                    b.Property<string>("Session")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("session");

                    b.Property<int>("Subjectid")
                        .HasColumnType("integer")
                        .HasColumnName("subjectid");

                    b.HasKey("Id")
                        .HasName("examschedules_pkey");

                    b.HasIndex("Classid");

                    b.HasIndex("Examid");

                    b.HasIndex("Subjectid");

                    b.ToTable("examschedules", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Feepayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amountpaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amountpaid");

                    b.Property<DateOnly?>("Paymentdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("paymentdate")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("Paymentmethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("paymentmethod");

                    b.Property<int>("Studentid")
                        .HasColumnType("integer")
                        .HasColumnName("studentid");

                    b.Property<string>("Transactionid")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("transactionid");

                    b.HasKey("Id")
                        .HasName("feepayments_pkey");

                    b.HasIndex(new[] { "Studentid" }, "idx_feepayments_student");

                    b.ToTable("feepayments", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Feestructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Academicyearid")
                        .HasColumnType("integer")
                        .HasColumnName("academicyearid");

                    b.Property<int>("Classid")
                        .HasColumnType("integer")
                        .HasColumnName("classid");

                    b.Property<string>("Feename")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("feename");

                    b.Property<decimal>("Totalamount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("totalamount");

                    b.HasKey("Id")
                        .HasName("feestructures_pkey");

                    b.HasIndex("Academicyearid");

                    b.HasIndex("Classid");

                    b.ToTable("feestructures", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Homework", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attachmenturl")
                        .HasColumnType("text")
                        .HasColumnName("attachmenturl");

                    b.Property<int>("Classid")
                        .HasColumnType("integer")
                        .HasColumnName("classid");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("Duedate")
                        .HasColumnType("date")
                        .HasColumnName("duedate");

                    b.Property<int>("Subjectid")
                        .HasColumnType("integer")
                        .HasColumnName("subjectid");

                    b.Property<int>("Teacherid")
                        .HasColumnType("integer")
                        .HasColumnName("teacherid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("homework_pkey");

                    b.HasIndex("Classid");

                    b.HasIndex("Subjectid");

                    b.HasIndex("Teacherid");

                    b.ToTable("homework", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Homeworksubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Homeworkid")
                        .HasColumnType("integer")
                        .HasColumnName("homeworkid");

                    b.Property<decimal?>("Marks")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("marks");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<int>("Studentid")
                        .HasColumnType("integer")
                        .HasColumnName("studentid");

                    b.Property<DateTime?>("Submittedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("submittedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Uploadedfileurl")
                        .HasColumnType("text")
                        .HasColumnName("uploadedfileurl");

                    b.Property<string>("Verificationstatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("verificationstatus");

                    b.HasKey("Id")
                        .HasName("homeworksubmissions_pkey");

                    b.HasIndex("Homeworkid");

                    b.HasIndex(new[] { "Studentid" }, "idx_homeworksubmission_student");

                    b.ToTable("homeworksubmissions", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Createdbyuserid")
                        .HasColumnType("integer")
                        .HasColumnName("createdbyuserid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("notifications_pkey");

                    b.HasIndex("Createdbyuserid");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Phonenumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("Relation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("relation");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("parents_pkey");

                    b.HasIndex(new[] { "Userid" }, "parents_userid_key")
                        .IsUnique();

                    b.ToTable("parents", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Parentdocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bloburl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bloburl");

                    b.Property<string>("Documenttype")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("documenttype");

                    b.Property<int>("Parentid")
                        .HasColumnType("integer")
                        .HasColumnName("parentid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<DateTime?>("Uploadedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("uploadedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("parentdocuments_pkey");

                    b.HasIndex("Parentid");

                    b.ToTable("parentdocuments", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Rolename")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rolename");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "Rolename" }, "roles_rolename_key")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Salary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Currentsalary")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("currentsalary");

                    b.Property<DateOnly?>("Lastsalarydate")
                        .HasColumnType("date")
                        .HasColumnName("lastsalarydate");

                    b.Property<int?>("Staffid")
                        .HasColumnType("integer")
                        .HasColumnName("staffid");

                    b.Property<int?>("Teacherid")
                        .HasColumnType("integer")
                        .HasColumnName("teacherid");

                    b.HasKey("Id")
                        .HasName("salaries_pkey");

                    b.HasIndex("Staffid");

                    b.HasIndex("Teacherid");

                    b.ToTable("salaries", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Joiningdate")
                        .HasColumnType("date")
                        .HasColumnName("joiningdate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Phonenumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phonenumber");

                    b.Property<int>("Stafftypeid")
                        .HasColumnType("integer")
                        .HasColumnName("stafftypeid");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("staff_pkey");

                    b.HasIndex("Stafftypeid");

                    b.HasIndex(new[] { "Userid" }, "staff_userid_key")
                        .IsUnique();

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Staffattendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attendancetype")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Userid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Userid");

                    b.ToTable("Staffattendances");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Stafftype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Typename")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("typename");

                    b.HasKey("Id")
                        .HasName("stafftypes_pkey");

                    b.HasIndex(new[] { "Typename" }, "stafftypes_typename_key")
                        .IsUnique();

                    b.ToTable("stafftypes", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Admissiondate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("admissiondate")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("Bloodgroup")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("bloodgroup");

                    b.Property<DateOnly?>("Dateofbirth")
                        .HasColumnType("date")
                        .HasColumnName("dateofbirth");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int?>("Parentid")
                        .HasColumnType("integer")
                        .HasColumnName("parentid");

                    b.Property<string>("Regno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("regno");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("students_pkey");

                    b.HasIndex("Parentid");

                    b.HasIndex(new[] { "Regno" }, "idx_students_regno");

                    b.HasIndex(new[] { "Regno" }, "students_regno_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Userid" }, "students_userid_key")
                        .IsUnique();

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Studentdocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bloburl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bloburl");

                    b.Property<string>("Documenttype")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("documenttype");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<int>("Studentid")
                        .HasColumnType("integer")
                        .HasColumnName("studentid");

                    b.Property<DateTime?>("Uploadedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("uploadedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("studentdocuments_pkey");

                    b.HasIndex("Studentid");

                    b.ToTable("studentdocuments", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Studentenrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Academicyearid")
                        .HasColumnType("integer")
                        .HasColumnName("academicyearid");

                    b.Property<int>("Classid")
                        .HasColumnType("integer")
                        .HasColumnName("classid");

                    b.Property<int?>("Rollnumber")
                        .HasColumnType("integer")
                        .HasColumnName("rollnumber");

                    b.Property<int>("Studentid")
                        .HasColumnType("integer")
                        .HasColumnName("studentid");

                    b.HasKey("Id")
                        .HasName("studentenrollments_pkey");

                    b.HasIndex("Academicyearid");

                    b.HasIndex("Classid");

                    b.HasIndex(new[] { "Studentid", "Academicyearid" }, "studentenrollments_studentid_academicyearid_key")
                        .IsUnique();

                    b.ToTable("studentenrollments", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Subjectname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subjectname");

                    b.HasKey("Id")
                        .HasName("subjects_pkey");

                    b.HasIndex(new[] { "Subjectname" }, "subjects_subjectname_key")
                        .IsUnique();

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Joiningdate")
                        .HasColumnType("date")
                        .HasColumnName("joiningdate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Phonenumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("Qualifications")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("qualifications");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("teachers_pkey");

                    b.HasIndex(new[] { "Userid" }, "teachers_userid_key")
                        .IsUnique();

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Teacherdocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bloburl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bloburl");

                    b.Property<string>("Documenttype")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("documenttype");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<int>("Teacherid")
                        .HasColumnType("integer")
                        .HasColumnName("teacherid");

                    b.Property<DateTime?>("Uploadedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("uploadedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("teacherdocuments_pkey");

                    b.HasIndex("Teacherid");

                    b.ToTable("teacherdocuments", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Teachersubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Classid")
                        .HasColumnType("integer")
                        .HasColumnName("classid");

                    b.Property<int>("Subjectid")
                        .HasColumnType("integer")
                        .HasColumnName("subjectid");

                    b.Property<int>("Teacherid")
                        .HasColumnType("integer")
                        .HasColumnName("teacherid");

                    b.HasKey("Id")
                        .HasName("teachersubjects_pkey");

                    b.HasIndex("Classid");

                    b.HasIndex("Subjectid");

                    b.HasIndex(new[] { "Teacherid", "Subjectid", "Classid" }, "teachersubjects_teacherid_subjectid_classid_key")
                        .IsUnique();

                    b.ToTable("teachersubjects", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Timetable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Classid")
                        .HasColumnType("integer")
                        .HasColumnName("classid");

                    b.Property<string>("Dayofweek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dayofweek");

                    b.Property<TimeOnly>("Endtime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("endtime");

                    b.Property<string>("Roomno")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("roomno");

                    b.Property<TimeOnly>("Starttime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("starttime");

                    b.Property<int>("Subjectid")
                        .HasColumnType("integer")
                        .HasColumnName("subjectid");

                    b.Property<int>("Teacherid")
                        .HasColumnType("integer")
                        .HasColumnName("teacherid");

                    b.HasKey("Id")
                        .HasName("timetables_pkey");

                    b.HasIndex("Classid");

                    b.HasIndex("Subjectid");

                    b.HasIndex("Teacherid");

                    b.ToTable("timetables", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool?>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<string>("Passwordhash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Resettoken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Resettokenexpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Roleid")
                        .HasColumnType("integer")
                        .HasColumnName("roleid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex("Roleid");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Usernotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Isread")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isread");

                    b.Property<int>("Notificationid")
                        .HasColumnType("integer")
                        .HasColumnName("notificationid");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("usernotifications_pkey");

                    b.HasIndex("Notificationid");

                    b.HasIndex("Userid");

                    b.ToTable("usernotifications", (string)null);
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Asset", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.Assettype", "Assettype")
                        .WithMany("Assets")
                        .HasForeignKey("Assettypeid")
                        .HasConstraintName("assets_assettypeid_fkey");

                    b.HasOne("SchoolERPManagementModelLibrary.Models.Class", "Assignedclass")
                        .WithMany("Assets")
                        .HasForeignKey("Assignedclassid")
                        .HasConstraintName("assets_assignedclassid_fkey");

                    b.Navigation("Assettype");

                    b.Navigation("Assignedclass");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Assetreport", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.Asset", "Asset")
                        .WithMany("Assetreports")
                        .HasForeignKey("Assetid")
                        .IsRequired()
                        .HasConstraintName("assetreports_assetid_fkey");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Attendance", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.Teacher", "Markedbyteacher")
                        .WithMany("Attendances")
                        .HasForeignKey("Markedbyteacherid")
                        .HasConstraintName("attendance_markedbyteacherid_fkey");

                    b.HasOne("SchoolERPManagementModelLibrary.Models.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("Studentid")
                        .IsRequired()
                        .HasConstraintName("attendance_studentid_fkey");

                    b.Navigation("Markedbyteacher");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Class", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.Teacher", "Classteacher")
                        .WithMany("Classes")
                        .HasForeignKey("Classteacherid")
                        .HasConstraintName("classes_classteacherid_fkey");

                    b.Navigation("Classteacher");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Exam", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.Academicyear", "Academicyear")
                        .WithMany("Exams")
                        .HasForeignKey("Academicyearid")
                        .HasConstraintName("exams_academicyearid_fkey");

                    b.Navigation("Academicyear");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Examresult", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.Exam", "Exam")
                        .WithMany("Examresults")
                        .HasForeignKey("Examid")
                        .IsRequired()
                        .HasConstraintName("examresults_examid_fkey");

                    b.HasOne("SchoolERPManagementModelLibrary.Models.Student", "Student")
                        .WithMany("Examresults")
                        .HasForeignKey("Studentid")
                        .IsRequired()
                        .HasConstraintName("examresults_studentid_fkey");

                    b.HasOne("SchoolERPManagementModelLibrary.Models.Subject", "Subject")
                        .WithMany("Examresults")
                        .HasForeignKey("Subjectid")
                        .IsRequired()
                        .HasConstraintName("examresults_subjectid_fkey");

                    b.Navigation("Exam");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Examschedule", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.Class", "Class")
                        .WithMany("Examschedules")
                        .HasForeignKey("Classid")
                        .IsRequired()
                        .HasConstraintName("examschedules_classid_fkey");

                    b.HasOne("SchoolERPManagementModelLibrary.Models.Exam", "Exam")
                        .WithMany("Examschedules")
                        .HasForeignKey("Examid")
                        .IsRequired()
                        .HasConstraintName("examschedules_examid_fkey");

                    b.HasOne("SchoolERPManagementModelLibrary.Models.Subject", "Subject")
                        .WithMany("Examschedules")
                        .HasForeignKey("Subjectid")
                        .IsRequired()
                        .HasConstraintName("examschedules_subjectid_fkey");

                    b.Navigation("Class");

                    b.Navigation("Exam");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Feepayment", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.Student", "Student")
                        .WithMany("Feepayments")
                        .HasForeignKey("Studentid")
                        .IsRequired()
                        .HasConstraintName("feepayments_studentid_fkey");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Feestructure", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.Academicyear", "Academicyear")
                        .WithMany("Feestructures")
                        .HasForeignKey("Academicyearid")
                        .IsRequired()
                        .HasConstraintName("feestructures_academicyearid_fkey");

                    b.HasOne("SchoolERPManagementModelLibrary.Models.Class", "Class")
                        .WithMany("Feestructures")
                        .HasForeignKey("Classid")
                        .IsRequired()
                        .HasConstraintName("feestructures_classid_fkey");

                    b.Navigation("Academicyear");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Homework", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.Class", "Class")
                        .WithMany("Homeworks")
                        .HasForeignKey("Classid")
                        .IsRequired()
                        .HasConstraintName("homework_classid_fkey");

                    b.HasOne("SchoolERPManagementModelLibrary.Models.Subject", "Subject")
                        .WithMany("Homeworks")
                        .HasForeignKey("Subjectid")
                        .IsRequired()
                        .HasConstraintName("homework_subjectid_fkey");

                    b.HasOne("SchoolERPManagementModelLibrary.Models.Teacher", "Teacher")
                        .WithMany("Homeworks")
                        .HasForeignKey("Teacherid")
                        .IsRequired()
                        .HasConstraintName("homework_teacherid_fkey");

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Homeworksubmission", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.Homework", "Homework")
                        .WithMany("Homeworksubmissions")
                        .HasForeignKey("Homeworkid")
                        .IsRequired()
                        .HasConstraintName("homeworksubmissions_homeworkid_fkey");

                    b.HasOne("SchoolERPManagementModelLibrary.Models.Student", "Student")
                        .WithMany("Homeworksubmissions")
                        .HasForeignKey("Studentid")
                        .IsRequired()
                        .HasConstraintName("homeworksubmissions_studentid_fkey");

                    b.Navigation("Homework");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Notification", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.User", "Createdbyuser")
                        .WithMany("Notifications")
                        .HasForeignKey("Createdbyuserid")
                        .HasConstraintName("notifications_createdbyuserid_fkey");

                    b.Navigation("Createdbyuser");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Parent", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.User", "User")
                        .WithOne("Parent")
                        .HasForeignKey("SchoolERPManagementModelLibrary.Models.Parent", "Userid")
                        .IsRequired()
                        .HasConstraintName("parents_userid_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Parentdocument", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.Parent", "Parent")
                        .WithMany("Parentdocuments")
                        .HasForeignKey("Parentid")
                        .IsRequired()
                        .HasConstraintName("parentdocuments_parentid_fkey");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Salary", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.Staff", "Staff")
                        .WithMany("Salaries")
                        .HasForeignKey("Staffid")
                        .HasConstraintName("salaries_staffid_fkey");

                    b.HasOne("SchoolERPManagementModelLibrary.Models.Teacher", "Teacher")
                        .WithMany("Salaries")
                        .HasForeignKey("Teacherid")
                        .HasConstraintName("salaries_teacherid_fkey");

                    b.Navigation("Staff");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Staff", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.Stafftype", "Stafftype")
                        .WithMany("Staff")
                        .HasForeignKey("Stafftypeid")
                        .IsRequired()
                        .HasConstraintName("staff_stafftypeid_fkey");

                    b.HasOne("SchoolERPManagementModelLibrary.Models.User", "User")
                        .WithOne("Staff")
                        .HasForeignKey("SchoolERPManagementModelLibrary.Models.Staff", "Userid")
                        .IsRequired()
                        .HasConstraintName("staff_userid_fkey");

                    b.Navigation("Stafftype");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Staffattendance", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.User", "User")
                        .WithMany("Staffattendances")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Student", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.Parent", "Parent")
                        .WithMany("Students")
                        .HasForeignKey("Parentid")
                        .HasConstraintName("students_parentid_fkey");

                    b.HasOne("SchoolERPManagementModelLibrary.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("SchoolERPManagementModelLibrary.Models.Student", "Userid")
                        .IsRequired()
                        .HasConstraintName("students_userid_fkey");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Studentdocument", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.Student", "Student")
                        .WithMany("Studentdocuments")
                        .HasForeignKey("Studentid")
                        .IsRequired()
                        .HasConstraintName("studentdocuments_studentid_fkey");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Studentenrollment", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.Academicyear", "Academicyear")
                        .WithMany("Studentenrollments")
                        .HasForeignKey("Academicyearid")
                        .IsRequired()
                        .HasConstraintName("studentenrollments_academicyearid_fkey");

                    b.HasOne("SchoolERPManagementModelLibrary.Models.Class", "Class")
                        .WithMany("Studentenrollments")
                        .HasForeignKey("Classid")
                        .IsRequired()
                        .HasConstraintName("studentenrollments_classid_fkey");

                    b.HasOne("SchoolERPManagementModelLibrary.Models.Student", "Student")
                        .WithMany("Studentenrollments")
                        .HasForeignKey("Studentid")
                        .IsRequired()
                        .HasConstraintName("studentenrollments_studentid_fkey");

                    b.Navigation("Academicyear");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Teacher", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("SchoolERPManagementModelLibrary.Models.Teacher", "Userid")
                        .IsRequired()
                        .HasConstraintName("teachers_userid_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Teacherdocument", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.Teacher", "Teacher")
                        .WithMany("Teacherdocuments")
                        .HasForeignKey("Teacherid")
                        .IsRequired()
                        .HasConstraintName("teacherdocuments_teacherid_fkey");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Teachersubject", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.Class", "Class")
                        .WithMany("Teachersubjects")
                        .HasForeignKey("Classid")
                        .IsRequired()
                        .HasConstraintName("teachersubjects_classid_fkey");

                    b.HasOne("SchoolERPManagementModelLibrary.Models.Subject", "Subject")
                        .WithMany("Teachersubjects")
                        .HasForeignKey("Subjectid")
                        .IsRequired()
                        .HasConstraintName("teachersubjects_subjectid_fkey");

                    b.HasOne("SchoolERPManagementModelLibrary.Models.Teacher", "Teacher")
                        .WithMany("Teachersubjects")
                        .HasForeignKey("Teacherid")
                        .IsRequired()
                        .HasConstraintName("teachersubjects_teacherid_fkey");

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Timetable", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.Class", "Class")
                        .WithMany("Timetables")
                        .HasForeignKey("Classid")
                        .IsRequired()
                        .HasConstraintName("timetables_classid_fkey");

                    b.HasOne("SchoolERPManagementModelLibrary.Models.Subject", "Subject")
                        .WithMany("Timetables")
                        .HasForeignKey("Subjectid")
                        .IsRequired()
                        .HasConstraintName("timetables_subjectid_fkey");

                    b.HasOne("SchoolERPManagementModelLibrary.Models.Teacher", "Teacher")
                        .WithMany("Timetables")
                        .HasForeignKey("Teacherid")
                        .IsRequired()
                        .HasConstraintName("timetables_teacherid_fkey");

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.User", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("Roleid")
                        .IsRequired()
                        .HasConstraintName("users_roleid_fkey");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Usernotification", b =>
                {
                    b.HasOne("SchoolERPManagementModelLibrary.Models.Notification", "Notification")
                        .WithMany("Usernotifications")
                        .HasForeignKey("Notificationid")
                        .IsRequired()
                        .HasConstraintName("usernotifications_notificationid_fkey");

                    b.HasOne("SchoolERPManagementModelLibrary.Models.User", "User")
                        .WithMany("Usernotifications")
                        .HasForeignKey("Userid")
                        .IsRequired()
                        .HasConstraintName("usernotifications_userid_fkey");

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Academicyear", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Feestructures");

                    b.Navigation("Studentenrollments");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Asset", b =>
                {
                    b.Navigation("Assetreports");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Assettype", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Class", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Examschedules");

                    b.Navigation("Feestructures");

                    b.Navigation("Homeworks");

                    b.Navigation("Studentenrollments");

                    b.Navigation("Teachersubjects");

                    b.Navigation("Timetables");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Exam", b =>
                {
                    b.Navigation("Examresults");

                    b.Navigation("Examschedules");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Homework", b =>
                {
                    b.Navigation("Homeworksubmissions");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Notification", b =>
                {
                    b.Navigation("Usernotifications");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Parent", b =>
                {
                    b.Navigation("Parentdocuments");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Staff", b =>
                {
                    b.Navigation("Salaries");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Stafftype", b =>
                {
                    b.Navigation("Staff");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Examresults");

                    b.Navigation("Feepayments");

                    b.Navigation("Homeworksubmissions");

                    b.Navigation("Studentdocuments");

                    b.Navigation("Studentenrollments");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Subject", b =>
                {
                    b.Navigation("Examresults");

                    b.Navigation("Examschedules");

                    b.Navigation("Homeworks");

                    b.Navigation("Teachersubjects");

                    b.Navigation("Timetables");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.Teacher", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Classes");

                    b.Navigation("Homeworks");

                    b.Navigation("Salaries");

                    b.Navigation("Teacherdocuments");

                    b.Navigation("Teachersubjects");

                    b.Navigation("Timetables");
                });

            modelBuilder.Entity("SchoolERPManagementModelLibrary.Models.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Parent");

                    b.Navigation("Staff");

                    b.Navigation("Staffattendances");

                    b.Navigation("Student");

                    b.Navigation("Teacher");

                    b.Navigation("Usernotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
