apiVersion: v1
kind: Service
metadata:
  name: ai-backend-service
  labels:
    app: ai-backend
spec:
  type: ClusterIP
  selector:
    app: ai-backend
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
