apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  labels:
    app: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: backend-api
          # The image name will be replaced by the CI/CD pipeline
          image: DOCKER_IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: KeyVault__Url
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KeyVaultUri
            - name: Stripe__SuccessUrl
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: StripeSuccessUrl
            - name: Stripe__CancelUrl
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: StripeCancelUrl
            - name: ConnectionStrings__Redis
              value: "redis-service:6379,abortConnect=false"
      # The secret name that contains ACR login credentials
      imagePullSecrets:
        - name: acr-auth
