name: Backend CI/CD to AKS

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'SchoolERPManagementAPI/**'
      - 'SchoolERPManagement*Library/**'
      - 'Dockerfile'
      - 'k8s/**'
      - '.github/workflows/backend-ci-cd.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME="${{ secrets.ACR_LOGIN_SERVER }}/backend-api:${{ github.sha }}"
        docker build -t $IMAGE_NAME -f Dockerfile .
        docker push $IMAGE_NAME

    - name: Set Kubernetes Context
      uses: azure/k8s-set-context@v3
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Update Kubernetes Deployment Image
      run: |
        # Replace the placeholder in the deployment file with the new image tag
        sed -i "s|DOCKER_IMAGE_PLACEHOLDER|${{ secrets.ACR_LOGIN_SERVER }}/backend-api:${{ github.sha }}|g" k8s/backend-deployment.yaml

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/backend-service.yaml
